import type { Metadata } from "next";
import "./globals.css";
import { balooChettan } from "./constants/font";
import "animate.css";

export const metadata: Metadata = {
  title: "Bao & Chau Wedding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${balooChettan.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
